# Generated by Django 4.1.7 on 2023-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_do_sal', '0002_roomreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='date',
            field=models.DateField(),
        ),
    ]
